getwd()
setwd("C:/Users/Naresh/Desktop/DATA/p1")
getwd()
data = read.table("household_power_consumption.txt",header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
datafiltered = subset(data,data$Date=="1/2/2007" | data$Date =="2/2/2007")
GlobalActivePower = as.numeric(datafiltered$Global_active_power)
Timeformat = strptime(paste(datafiltered$Date, datafiltered$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
plot(Timeformat, datafiltered$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
with(datafiltered,lines(Timeformat,datafiltered$Sub_metering_1))
with(datafiltered,lines(Timeformat,datafiltered$Sub_metering_2,col="red"))
with(datafiltered,lines(Timeformat,datafiltered$Sub_metering_3,col="blue"))
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
